// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	GetIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) ([]Identity, error)
	GetIdentityByProviderID(ctx context.Context, arg GetIdentityByProviderIDParams) (Identity, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone pgtype.Text) (User, error)
	RevokeRefreshToken(ctx context.Context, id pgtype.UUID) error
	RevokeRefreshTokenFamily(ctx context.Context, family pgtype.UUID) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
