// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (user_id, provider, provider_id, email, name)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, provider, provider_id, email, name, created_at
`

type CreateIdentityParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
	Email      pgtype.Text `json:"email"`
	Name       pgtype.Text `json:"name"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderID,
		arg.Email,
		arg.Name,
	)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getIdentitiesByUserID = `-- name: GetIdentitiesByUserID :many
SELECT id, user_id, provider, provider_id, email, name, created_at FROM identities WHERE user_id = $1
`

func (q *Queries) GetIdentitiesByUserID(ctx context.Context, userID pgtype.UUID) ([]Identity, error) {
	rows, err := q.db.Query(ctx, getIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Identity
	for rows.Next() {
		var i Identity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderID,
			&i.Email,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdentityByProviderID = `-- name: GetIdentityByProviderID :one
SELECT id, user_id, provider, provider_id, email, name, created_at FROM identities WHERE provider = $1 AND provider_id = $2
`

type GetIdentityByProviderIDParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetIdentityByProviderID(ctx context.Context, arg GetIdentityByProviderIDParams) (Identity, error) {
	row := q.db.QueryRow(ctx, getIdentityByProviderID, arg.Provider, arg.ProviderID)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
